# Generated by Django 4.2.16 on 2024-12-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_order_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order'),
        ),
    ]
